// [auto-generated by scripts/sync-region-functions.mjs]
// EdgeOne Pages 边缘函数：按客户端地理位置拦截页面
// 由 scripts/sync-region-functions.mjs 依据 src/config/regionBlockConfig.ts 生成，
// 请勿直接编辑本文件——修改 regionBlockConfig.ts 后重新构建即可

const BLOCKED_COUNTRY_CODES = ["CN"];
const ROUTE = "/dynamic/";

export async function onRequest(context) {
	const geo = context.request.eo && context.request.eo.geo;
	const code = String(
		(geo && (geo.countrycode || geo.countryCode)) || "",
	).toUpperCase();
	if (BLOCKED_COUNTRY_CODES.indexOf(code) >= 0) {
		return new Response("404 Not Found", { status: 404 });
	}
	// 非拦截地区：fetch(request) 访问 EdgeOne 节点缓存/回源获取 Pages 静态资源
	// （HOST 与客户端请求一致，符合回源条件；CLI 本地调试不支持该特性，线上可用）
	return fetch(context.request);
}
