// [auto-generated by scripts/sync-region-functions.mjs]
// EdgeOne Pages 边缘函数：区域探测接口
// 由 scripts/sync-region-functions.mjs 生成，请勿直接编辑本文件

export function onRequest(context) {
	const geo = context.request.eo && context.request.eo.geo;
	// 字段名 countryCodeAlpha2 由 EdgeOne 边缘函数 GEO 属性定义（ISO 3166-1 alpha-2）
	const code = String(
		(geo && geo.countryCodeAlpha2) || "",
	).toUpperCase();
	return new Response(JSON.stringify({ region: code }), {
		headers: {
			"content-type": "application/json; charset=utf-8",
			"cache-control": "no-store",
		},
	});
}
