// [auto-generated by scripts/sync-region-functions.mjs]
// EdgeOne Pages 边缘函数：按客户端地理位置拦截页面
// 由 scripts/sync-region-functions.mjs 依据 src/config/regionBlockConfig.ts 生成，
// 请勿直接编辑本文件——修改 regionBlockConfig.ts 后重新构建即可

const BLOCKED_COUNTRY_CODES = ["CN"];
const ROUTE = "/sponsor/";

export async function onRequest(context) {
	const geo = context.request.eo && context.request.eo.geo;
		// 字段名 countryCodeAlpha2 由 EdgeOne 边缘函数 GEO 属性定义（ISO 3166-1 alpha-2）
		// 参考：https://cloud.tencent.com/document/product/1552/81902
		const code = String(
			(geo && geo.countryCodeAlpha2) || "",
		).toUpperCase();
	if (BLOCKED_COUNTRY_CODES.indexOf(code) >= 0) {
		// 大陆访问：静默重定向回首页（不展示 404 错误页，不缓存该响应）
		const home = new URL("/", context.request.url).toString();
		const res = Response.redirect(home, 302);
		res.headers.set("Cache-Control", "no-store");
		return res;
	}
	// 非拦截地区：fetch(request) 访问 EdgeOne 节点缓存/回源获取 Pages 静态资源
	// （HOST 与客户端请求一致，符合回源条件；CLI 本地调试不支持该特性，线上可用）
	return fetch(context.request);
}
